#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Nov 03, 2021 03:51:47 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background skyblue4 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 777x657+763+58
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "NasaStills - Tk"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 500 -highlightcolor black -width 713 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background skyblue3 -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab46" "labelImage" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 2 -y 2 -width 708 -relwidth 0 -height 488 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra45
    checkbutton $top.che47 \
        -activebackground skyblue3 -activeforeground black -anchor w \
        -background skyblue4 -command on_chkAspect -compound left \
        -foreground antiquewhite2 -highlightcolor black -justify left \
        -selectcolor skyblue4 -text {Correct Aspect Ratio} -variable che47 
    vTcl:DefineAlias "$top.che47" "chkAspect" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che48 \
        -activebackground skyblue3 -activeforeground black -anchor w \
        -background skyblue4 -command on_chkTime -compound left \
        -foreground antiquewhite2 -highlightcolor black -justify left \
        -selectcolor skyblue4 -text {Auto-reload every (seconds)} \
        -variable che48 
    vTcl:DefineAlias "$top.che48" "chkTime" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground skyblue3 -activeforeground black \
        -background skyblue4 -borderwidth 2 -command on_btnExit \
        -foreground #ffffff -highlightbackground skyblue3 \
        -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but49" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    spinbox $top.spi50 \
        -activebackground #f9f9f9 -background white -command on_spinChange \
        -font TkDefaultFont -foreground black -from 45.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinbox -to 300.0 -wrap 1 
    vTcl:DefineAlias "$top.spi50" "Spinbox1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground skyblue3 -activeforeground black \
        -background skyblue4 -borderwidth 2 -command on_btnReload \
        -foreground #ffffff -highlightbackground skyblue3 \
        -highlightcolor black -text Reload 
    vTcl:DefineAlias "$top.but51" "btnReload" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground skyblue3 -activeforeground black \
        -background skyblue4 -borderwidth 2 -command on_btnSave \
        -foreground #ffffff -highlightbackground skyblue3 \
        -highlightcolor black -text Save 
    vTcl:DefineAlias "$top.but52" "btnSave" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground skyblue3 -activeforeground black \
        -background skyblue4 -borderwidth 2 -command on_btnSet \
        -foreground #ffffff -highlightbackground skyblue3 \
        -highlightcolor black -text Set 
    vTcl:DefineAlias "$top.but53" "btnSet" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 31 -y 10 -width 714 -relwidth 0 -height 492 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che47 \
        -in $top -x 110 -y 530 -width 187 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 110 -y 600 -width 227 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 493 -y 526 -width 85 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.spi50 \
        -in $top -x 360 -y 600 -width 58 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 406 -y 526 -width 75 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 319 -y 526 -width 73 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 440 -y 595 -width 73 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

